### ISSUE TITLE
Need more documentation

### ISSUE THREAD

**Issue by ehayun** [ausimian/stagger#1]
Thank you for your work
This seems very promising, as a small queue 
Still, can you add a detailed example as an publisher and as a consumer

I want to be able to update the queue in one app and read it in another app

Thanks

**Comment by ausimian** [comment]
Hi @ehayun ,

Thank for the feedback. I'll see what I can do to make things clearer in the documentation. In reference to your comment regarding updating in one application and reading in another - it won't make any difference to the existing samples. 

Providing your two applications have some mechanism for agreeing on the path of the file, the updating application would open the queue as follows:
```elixir
# open the queue
{:ok, producer} = Stagger.open("/path/to/the/file")

# write the message
:ok = Stagger.write(producer, msg)
```
And your reading application might subscribe like this:
```elixir
# create the consumer
{:ok, consumer} = Consumer.start_link()

# open the queue
{:ok, producer} = Stagger.open("/path/to/the/file")

# connect the consumer to the producer
{:ok, subscription} = GenStage.subscribe(consumer, to: producer)
```

**Comment by ehayun** [comment]
Thanks
I will try that
The thing is that in the docs there is no sigh for Consumer 
Now it is clearer
